-- 000003_insert_muscle_groups_and_equipment.up.sql

INSERT INTO muscle_groups (id, name) VALUES
('muscle_group_chest', 'Chest'),
('muscle_group_lats', 'Lats'),
('muscle_group_traps', 'Traps'),
('muscle_group_front_delts', 'Front delts'),
('muscle_group_side_delts', 'Side delts'),
('muscle_group_rear_delts', 'Rear delts'),
('muscle_group_biceps', 'Biceps'),
('muscle_group_triceps', 'Triceps'),
('muscle_group_forearms', 'Forearms'),
('muscle_group_abs', 'Abs'),
('muscle_group_obliques', 'Obliques'),
('muscle_group_lower_back', 'Lower back'),
('muscle_group_glutes', 'Glutes'),
('muscle_group_quads', 'Quads'),
('muscle_group_hamstrings', 'Hamstrings'),
('muscle_group_calves', 'Calves'),
('muscle_group_hip_flexors', 'Hip flexors'),
('muscle_group_adductors', 'Adductors'),
('muscle_group_rhomboids', 'Rhomboids'),
('muscle_group_rotator_cuff', 'Rotator cuff'),
('muscle_group_spinal_erectors', 'Spinal erectors'),
('muscle_group_neck', 'Neck');

INSERT INTO equipment (id, name) VALUES
('equipment_olympic_barbell', 'Olympic barbell'),
('equipment_ez_curl_bar', 'EZ curl bar'),
('equipment_bench', 'Bench'),
('equipment_cable_machine', 'Cable machine'),
('equipment_pull_up_bar', 'Pull-up bar'),
('equipment_dumbbells', 'Dumbbells'),
('equipment_pec_deck_machine', 'Pec deck machine'),
('equipment_lat_pulldown_machine', 'Lat pulldown machine'),
('equipment_bench_press_station', 'Bench press station'),
('equipment_power_rack', 'Power rack'),
('equipment_seated_row_machine', 'Seated row machine'),
('equipment_leg_press_machine', 'Leg press machine'),
('equipment_leg_extension_machine', 'Leg extension machine'),
('equipment_leg_curl_machine', 'Leg curl machine'),
('equipment_calf_raise_machine', 'Calf raise machine'),
('equipment_preacher_curl_bench', 'Preacher curl bench'),
('equipment_dip_station', 'Dip station'),
('equipment_kettlebells', 'Kettlebells'),
('equipment_tricep_pushdown_rope', 'Tricep pushdown rope'),
('equipment_back_extension_bench', 'Back extension bench'),
('equipment_ab_bench', 'Ab bench'),
('equipment_trap_bar', 'Trap bar'),
('equipment_safety_squat_bar', 'Safety squat bar'),
('equipment_weight_plates', 'Weight plates');